### ISSUE TITLE
Deleting a custom icon might not actually be deleting it in some cases

### ISSUE THREAD

**Issue by elindydotcom** [Simple-Press/simple-press#118]
**How to reproduce**
Upload an icon on the FORUM->FORUMS->CUSTOM ICONS with filename 01.png.
Delete the icon.
Upload a DIFFERENT icon using the same filename.
The original icon appears instead of the new icon.

Additionally, on the new upload, the DELETE operation does not work until the screen is refereshed.

**Comment by kashifishfaq** [comment]
Issue#118 fixed.
