### ISSUE TITLE
Admin panel overlaps search bar on mobile devices

### ISSUE THREAD

**Issue by onefloid** [Simple-Press/simple-press#148]
If you are using the Modern 2020 1.4.0 theme and are at the top of a page, the Admin panel overlaps the search bar. 

The reason for this is that the admin panel has the higher z-index. So you can't close the search bar and on other devices it was not possible to enter a search. 

![image](https://github.com/Simple-Press/simple-press/assets/33193059/044a56f1-183f-4703-8d7e-b173f3126eba)

The problem can be fixed by increasing the z-index in modern-2020-mobile.php to 999999. 

![image](https://github.com/Simple-Press/simple-press/assets/33193059/202f2a48-96a8-4819-ab0e-0b0bf24d6549)

I did not find the issue in this repo. If I missed something, please let me know. If so, I'll be happy to create a pull request. 

P.s. On the iPhone, the search is always placed at the top. I don't know why yet, but that's another problem.  It makes the overlapping admin bar even worse. 

Versions:
SimplePress 6.9.1
WordPress: 6.2.2
Theme: GeneratePress 3.3.0
PHP 7.4.3
OS: Linux
Browser: Chromium Device iPhone SE

**Comment by nigobo** [comment]
Hi @onefloid 

Thanks for posting about the issue and suggesting a fix. We will have a look at it and get back to you.

Best regards,
Joakim @ Simple:Press

**Comment by nigobo** [comment]
We released `1.4.3` that contains a fix for this issue. The zip can be downloaded here https://simple-press.com/downloads/modern-2020-theme/

Best regards,
Joakim @ Simple:Press
